---
title: "Complaints Final"
author: "Yuhan Wu"
date: "6/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
```

```{r get-data, include=FALSE}
raw_data <- read_csv("https://raw.githubusercontent.com/Financial-Times/police-misconduct-complaints-analysis/main/output/philly_clean.csv") %>% 
  select(officer_id, po_race, po_sex)
```

```{r, clean_data}
 clean_data <- raw_data %>% 
  group_by(officer_id) %>% 
  summarise(total = n()) %>% 
  mutate(compl_dec = ntile(total, 10)) %>% 
  group_by(compl_dec) %>% 
  summarize(compl_total = sum(total)) %>% 
  mutate(compl_percentage = compl_total/sum(compl_total))

 
```

```{r}
clean_data%>%
  ggplot(mapping=aes(x=compl_dec, y= compl_percentage))+
  geom_col()+
  scale_x_continuous(breaks= c(1:10))+
  scale_y_continuous(labels = scales::percent)+
  labs(title="Philadelphia Police complaints in Percentage ", subtitle = "One Deciles has double amounts of the second most deciles of complaints",x="Deciles of Officer",y="Percentage of Complaints",caption = "Financial Time")+
theme_linedraw()
```



